-- MySQL Script generated by MySQL Workbench
-- Sun Jul  3 16:59:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ExpressFood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ExpressFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ExpressFood` DEFAULT CHARACTER SET utf8 ;
USE `ExpressFood` ;

-- -----------------------------------------------------
-- Table `ExpressFood`.`TypeCompte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`TypeCompte` (
  `idTypeCompte` TINYINT(5) NOT NULL,
  `libelleTypeCompte` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeCompte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `voie` VARCHAR(255) NOT NULL,
  `complement` VARCHAR(255) NULL,
  `codePostal` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Compte` (
  `idCompte` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `motDePasse` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(10) NOT NULL,
  `idTypeCompte` TINYINT(5) NOT NULL,
  `idAdresse` INT NOT NULL,
  PRIMARY KEY (`idCompte`),
  INDEX `idTypeCompte_idx` (`idTypeCompte` ASC) VISIBLE,
  INDEX `idAdresse_idx` (`idAdresse` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `idCompte` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  INDEX `idCompte_idx` (`idCompte` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Livreur` (
  `idLivreur` INT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  INDEX `idLivreur_idx` (`idLivreur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Chef` (
  `idChef` INT NOT NULL,
  PRIMARY KEY (`idChef`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Livraison` (
  `idLivraison` INT NOT NULL AUTO_INCREMENT,
  `heure` DATETIME NOT NULL,
  `idCommande` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `idLivreur` INT NOT NULL,
  PRIMARY KEY (`idLivraison`),
  INDEX `idCommande_idx` (`idCommande` ASC) VISIBLE,
  INDEX `idLivreur_idx` (`idLivreur` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`Plat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`Plat` (
  `idplat` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `prixHt` FLOAT NOT NULL,
  `idChef` INT NULL,
  PRIMARY KEY (`idplat`),
  INDEX `idChef_idx` (`idChef` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExpressFood`.`LigneCommande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpressFood`.`LigneCommande` (
  `idLigneCommande` INT NOT NULL AUTO_INCREMENT,
  `idCommande` INT NULL,
  `idPlat` INT NULL,
  PRIMARY KEY (`idLigneCommande`),
  INDEX `idCommande_idx` (`idCommande` ASC) VISIBLE,
  INDEX `idPlat_idx` (`idPlat` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
